# Simple Calculator ADD

In [1]:
from tkinter import *
window=Tk()

In [2]:
def addition():
    a=float(entry1.get())
    b=float(entry2.get())
    c=a+b
    entry3.insert(0,c)  

In [3]:
def delete():
    entry1.delete(0,END)
    entry2.delete(0,END)
    entry3.delete(0,END)
    

In [4]:
#getting two no. and adding them ,i need two labels
label1=Label(window,text="Enter No.1: ")
label2=Label(window,text="Enter No.2: ")


In [5]:
entry1=Entry(window)
entry2=Entry(window)
add=Button(window,text="ADD",command=addition)
entry3=Entry(window)
clear=Button(window,text="CLEAR",command=delete)

In [6]:
label1.grid(row=0,column=0)
label2.grid(row=1,column=0)
entry1.grid(row=0,column=1)
entry2.grid(row=1,column=1)
add.grid(row=2,column=0)
entry3.grid(row=2,column=1)
clear.grid(row=3,column=0)

In [7]:
window.mainloop()

# Simple Calculator ADD, SUB, MUL, DIV, MOD

In [8]:
from tkinter import *

In [9]:
window=Tk()

In [10]:
def add():
    a=int(entry1.get())
    b=int(entry2.get())
    c=a+b
    result_plus.insert(0,c)

def subtract():
    a=int(entry1.get())
    b=int(entry2.get())
    c=a-b
    result_sub.insert(0,c)
    
def multiply():
    a=int(entry1.get())
    b=int(entry2.get())
    c=a*b
    result_mul.insert(0,c)  
            
def divide():
    a=int(entry1.get())
    b=int(entry2.get())
    c=a/b
    result_div.insert(0,c)
    
def modulo():
    a=int(entry1.get())
    b=int(entry2.get())
    c=a%b
    result_mod.insert(0,c)

In [11]:
label1=Label(window,text="Enter first number:")
label1.pack( padx=10, pady=10)
entry1=Entry(window)
entry1.pack(padx=10, pady=10)
label2=Label(window,text="Enter second number:")
label2.pack( padx=10, pady=10)
entry2=Entry(window)
entry2.pack(padx=10, pady=10)
button_plus=Button(window,text="+",command=add)
button_plus.pack( padx=10, pady=10)
result_plus=Entry(window)
result_plus.pack(padx=10, pady=10)
button_sub=Button(window,text="-",command=subtract)
button_sub.pack(padx=10, pady=10)
result_sub=Entry(window)
result_sub.pack(padx=10, pady=10)
button_mul=Button(window,text="*",command=multiply)
button_mul.pack(padx=10, pady=10)
result_mul=Entry(window)
result_mul.pack(padx=10, pady=10)
button_div=Button(window,text="/",command=divide,)
button_div.pack(padx=10, pady=10)
result_div=Entry(window)
result_div.pack(padx=10, pady=10)
button_mod=Button(window,text="%",command=modulo)
button_mod.pack(padx=10, pady=10)
result_mod=Entry(window)
result_mod.pack(padx=10, pady=10)

In [12]:
def clear_entries():
    entry1.delete(0,END)
    entry2.delete(0,END)
    result_plus.delete(0,END)
    result_sub.delete(0,END)
    result_mul.delete(0,END)
    result_div.delete(0,END)
    result_mod.delete(0,END)    
clear_button=Button(window,text="Clear All",command=clear_entries)
clear_button.pack()

In [13]:
window.mainloop()

# Simple Calculator ADD, SUB, MUL, DIV Using Grid

In [14]:
from tkinter import *
window=Tk()

In [15]:
def addition():
    a=float(entry1.get())
    b=float(entry2.get())
    c=a+b
    result_plus.insert(0,c)
    
def subtraction():
    a=float(entry1.get())
    b=float(entry2.get())
    e=a-b
    result_sub.insert(0,e)              
    
def multiplication():
    a=float(entry1.get())
    b=float(entry2.get())
    f=a*b
    result_mul.insert(0,f)              
    
def division():
    a=float(entry1.get())
    b=float(entry2.get())
    g=a/b
    result_div.insert(0,g) 
def modulo():
    a=float(entry1.get())
    b=float(entry2.get())
    h=a%b
    result_mod.insert(0,h)        


In [16]:
def delete():
    entry1.delete(0,END)
    entry2.delete(0,END)
    result_plus.delete(0,END)
    result_sub.delete(0,END)
    result_mul.delete(0,END)
    result_div.delete(0,END)
    result_mod.delete(0,END)    

In [17]:
label1=Label(window,text="Enter No.1: ", bg="blue", fg="white",padx=20,pady=20)
label2=Label(window,text="Enter No.2: ", bg="red", fg="white",padx=20,pady=20)

entry1=Entry(window)
entry2=Entry(window)
label1.grid(row=0,column=0)
label2.grid(row=1,column=0)
entry1.grid(row=0,column=1)
entry2.grid(row=1,column=1)
add=Button(window,text="Add",command=addition)
subtraction=Button(window,text="Sub",command=subtraction)
multiplication=Button(window,text="Mul",command=multiplication)
division=Button(window,text="Div",command=division)
modulo=Button(window,text="Mod",command=modulo)
clear=Button(window,text="Clear All",command=delete)
multiplication.grid(row=2,column=2,padx=20,pady=20)
division.grid(row=3,column=2,padx=20,pady=20)
modulo.grid(row=4,column=0,padx=20,pady=20)
add.grid(row=2,column=0,padx=20,pady=20)
subtraction.grid(row=3,column=0,padx=20,pady=20)
result_plus=Entry(window)
result_plus.grid(row=2,column=1)
result_sub=Entry(window)
result_sub.grid(row=3,column=1)
result_mul=Entry(window)
result_mul.grid(row=2,column=3)
result_div=Entry(window)    
result_div.grid(row=3,column=3) 
result_mod=Entry(window)
result_mod.grid(row=4,column=1) 
clear=Button(window,text="Clear All",command=delete)
clear.grid(row=5, column=0)

In [18]:
window.mainloop()

# Simple Calculator Sin(), Cos(), Tan(), Log(), Ln()

In [19]:
from tkinter import *
import math

In [20]:
def sin():
    imanshu.delete(0, END)
    imanshu.insert(0, round(math.sin(math.radians(float(entry1.get()))), 4))

def cos():
    imanshu.delete(0, END)
    imanshu.insert(0, round(math.cos(math.radians(float(entry1.get()))), 4))

def tan():
    imanshu.delete(0, END)
    imanshu.insert(0, round(math.tan(math.radians(float(entry1.get()))), 4))

def log():
    imanshu.delete(0, END)
    imanshu.insert(0, round(math.log10(float(entry1.get())), 4))
def ln():
    imanshu.delete(0, END)
    imanshu.insert(0, round(math.log(float(entry1.get())), 4))

def clear():
    entry1.delete(0, END)
    imanshu.delete(0, END)

In [21]:
window = Tk()
window.title("Imansh Calculator")

Label(window, text="Enter Value (Degrees)", bg="blue", fg="white").pack(pady=20)
entry1 = Entry(window)
entry1.pack(pady=20)

Label(window, text="Final Result", bg="red", fg="black").pack(pady=20)
imanshu = Entry(window)
imanshu.pack(pady=20) 

In [22]:
rtmnu = Frame(window)
rtmnu.pack(pady=20) 

Button(rtmnu, text="sin( )", command=sin).grid(row=0, column=0, padx=20, pady=20)
Button(rtmnu, text="cos( )", command=cos).grid(row=0, column=1, padx=20, pady=20)
Button(rtmnu, text="tan( )", command=tan).grid(row=0, column=2, padx=20, pady=20)
Button(rtmnu, text="log( )",command=log).grid(row=1, column=0, padx=20, pady=20)
Button(rtmnu, text="ln( )", command=ln).grid(row=1, column=1, padx=20, pady=20)
Button(window, text="Clear All", command=clear).pack(padx=20, pady=60)


In [23]:
window.mainloop()

# Simple Calculator Sin(), Cos(), Tan(), Log(), Ln() Using Grid

In [24]:
from tkinter import *
import math

In [25]:
def sin():
    imanshu.insert(0, round(math.sin(math.radians(float(entry1.get()))), 4))

def cos():
    imanshu.insert(0, round(math.cos(math.radians(float(entry1.get()))), 4))

def tan():
    imanshu.insert(0, round(math.tan(math.radians(float(entry1.get()))), 4))

def log():
    imanshu.insert(0, round(math.log10(float(entry1.get())), 4))
    
def ln():
    imanshu.insert(0, round(math.log(float(entry1.get())), 4))

def clear():
    entry1.delete(0, END)
    imanshu.delete(0, END)

In [26]:
window = Tk()
window.title("Imansh Calculator")

Label(window, text="Enter Value (Degrees)", bg="blue", fg="white").grid(row=0, column=0, columnspan=3, pady=10)

entry1 = Entry(window)
entry1.grid(row=1, column=0, columnspan=3, pady=10)

Label(window, text="Final Result", bg="red", fg="black").grid(row=2, column=0, columnspan=3, pady=10)

imanshu = Entry(window)
imanshu.grid(row=3, column=0, columnspan=3, pady=10)

rtmnu = Frame(window)
rtmnu.grid(row=4, column=0, columnspan=3, pady=10)

Button(rtmnu, text="sin()", width=10, command=sin).grid(row=0, column=0, padx=10, pady=10)

Button(rtmnu, text="cos()", width=10, command=cos).grid(row=0, column=1, padx=10, pady=10)

Button(rtmnu, text="tan()", width=10, command=tan).grid(row=0, column=2, padx=10, pady=10)

Button(rtmnu, text="log()", width=10, command=log).grid(row=1, column=0, padx=10, pady=10)

Button(rtmnu, text="ln()", width=10, command=ln).grid(row=1, column=1, padx=10, pady=10)

Button(window, text="Clear All", width=20, command=clear).grid(row=5, column=0, columnspan=3, pady=20)

In [27]:
window.mainloop()

# Simple Calculator Sin(), Cos(), Tan(), Log(), Ln() Using Grid and Each Result Separate

In [28]:
from tkinter import *
import math

In [29]:
window = Tk()
window.title("Imansh Calculator")

''

In [30]:
def sin_val():
    v = float(entry.get())
    sin_result.delete(0, END)
    sin_result.insert(0, math.sin(math.radians(v)))

def cos_val():
    v = float(entry.get())
    cos_result.delete(0, END)
    cos_result.insert(0, math.cos(math.radians(v)))

def tan_val():
    v = float(entry.get())
    tan_result.delete(0, END)
    tan_result.insert(0, math.tan(math.radians(v)))

def log_val():
    v = float(entry.get())
    log_result.delete(0, END)
    log_result.insert(0, math.log10(v))

def ln_val():
    v = float(entry.get())
    ln_result.delete(0, END)
    ln_result.insert(0, math.log(v))

In [31]:
def clear():
    entry.delete(0, END)
    sin_result.delete(0, END)
    cos_result.delete(0, END)
    tan_result.delete(0, END)
    log_result.delete(0, END)
    ln_result.delete(0, END)

In [32]:
Label(window, text="Enter Value (Degrees)", bg="blue", fg="white").grid(row=0, column=0, columnspan=3, pady=10)

entry = Entry(window)
entry.grid(row=1, column=0, columnspan=3, pady=10)

In [33]:
Button(window, text="sin()", width=10, command=sin_val).grid(row=2, column=0, pady=5)
sin_result = Entry(window)
sin_result.grid(row=2, column=1, padx=2, pady=5)

Button(window, text="cos()", width=10, command=cos_val).grid(row=3, column=0, pady=5)
cos_result = Entry(window)
cos_result.grid(row=3, column=1, padx=2, pady=5)

Button(window, text="tan()", width=10, command=tan_val).grid(row=4, column=0, pady=5)
tan_result = Entry(window)
tan_result.grid(row=4, column=1, padx=2, pady=5)
Button(window, text="log()", width=10, command=log_val).grid(row=5, column=0, pady=5)
log_result = Entry(window)
log_result.grid(row=5, column=1, padx=2, pady=5)

Button(window, text="ln()", width=10, command=ln_val) .grid(row=6, column=0, pady=5)
ln_result = Entry(window)
ln_result.grid(row=6, column=1, padx=2, pady=5)
Button(window, text="Clear All", width=20, command=clear).grid(row=7, column=0, columnspan=3, pady=20)

In [34]:
window.mainloop()

# Ahm | Advanced Calculator

In [35]:
import tkinter as tk
import math

In [36]:
def add_value(value):
    entry.insert(tk.END, value)

def backspace():
    text = entry.get()
    entry.delete(0, tk.END)
    entry.insert(tk.END, text[:-1])

def calculate():
    try:
        result = eval(entry.get())
        entry.delete(0, tk.END)
        entry.insert(tk.END, result)
    except:
        entry.delete(0, tk.END)
        entry.insert(tk.END, "Error")

def sin():
    value = float(entry.get())
    entry.delete(0, tk.END)
    entry.insert(tk.END, math.sin(math.radians(value)))

def cos():
    value = float(entry.get())
    entry.delete(0, tk.END)
    entry.insert(tk.END, math.cos(math.radians(value)))

def tan():
    value = float(entry.get())
    entry.delete(0, tk.END)
    entry.insert(tk.END, math.tan(math.radians(value)))

def sqrt():
    value = float(entry.get())
    entry.delete(0, tk.END)
    entry.insert(tk.END, math.sqrt(value))
    
def clear():
    entry.delete(0, tk.END)

In [37]:
window = tk.Tk()
window.title("AI | Advanced Calculator")

''

In [38]:
entry = tk.Entry(window, font=("Times New Roman", 20), justify="right", bd=10)
entry.grid(row=0, column=0, columnspan=4, padx=10, pady=20, ipady=15)
btn_style = {"font": ("Arial", 14), "bg": "#E4E7E7", "fg": "black", "padx": 20, "pady": 20}

In [39]:
buttons = [
    ("7", 1, 0), ("8", 1, 1), ("9", 1, 2), ("/", 1, 3),
    ("4", 2, 0), ("5", 2, 1), ("6", 2, 2), ("*", 2, 3),
    ("1", 3, 0), ("2", 3, 1), ("3", 3, 2), ("-", 3, 3),
    ("0", 4, 0), (".", 4, 1), ("=", 4, 2), ("+", 4, 3),
    ("(", 5, 0), (")", 5, 1), ("C", 5, 2), ("⌫", 5, 3),
    ("sin", 6, 0), ("cos", 6, 1), ("tan", 6, 2), ("√", 6, 3)
]

In [40]:
for text, row, col in buttons:
    if text == "=":
        cmd = calculate
    elif text == "C":
        cmd = clear
    elif text == "⌫":
        cmd = backspace
    elif text == "sin ()":
        cmd = sin
    elif text == "cos ()":
        cmd = cos
    elif text == "tan":
        cmd = tan
    elif text == "√sqrt":
        cmd = sqrt
    else:
        cmd = lambda x=text: add_value(x)
    tk.Button(window, text=text, command=cmd, **btn_style).grid(row=row, column=col, sticky="nsew")

In [41]:
window.mainloop()

# Ahm| CSV File Explore

In [42]:
from tkinter import *
from csv import *
from tkinter import messagebox

In [43]:
window=Tk()
window.title("Simple| Data Entry")

''

In [44]:
with open(r"C:\Users\dearh\Downloads\imanshu 0321.csv","w") as file:
        Writer=writer(file)  #writer function is from csv module
        Writer.writerow(["name","age","mo.no","gender","City"])
        
def Add():
    if not validate_entries():
        return
    messagebox.showinfo("Info", "Data ready to save")

def Save():
    temp_list = [entry1.get(), entry2.get(), entry3.get(), entry4.get(), entry5.get()]
    #=["kunal","pune"...],["ritesh"]
    global mainlist
    if 'mainlist' not in globals():
        mainlist = []
    # Check if the data already exists in mainlist
    if temp_list not in mainlist:
        mainlist.append(temp_list)
    # messagebox.showinfo("Info", "Data added successfully")
        with open(r"C:\Users\dearh\Downloads\imanshu 0321.csv","a",newline='') as file:
            Writer=writer(file)
            Writer.writerow(temp_list)
        messagebox.showinfo("Info", "Data saved successfully!")
    else:
        messagebox.showinfo("Info", "Data already exists") 

def validate_entries():
    if (
        entry1.get() == "" or
        entry2.get() == "" or
        entry3.get() == "" or
        entry4.get() == "" or
        entry5.get() == ""
    ):
        messagebox.showwarning("Warning", "Please fill all the fields")
        return False
    return True

def Exit():
    window.quit()
    window.destroy()

In [45]:
def Clear():
    entry1.delete(0,END)
    entry2.delete(0,END)
    entry3.delete(0,END)
    entry4.delete(0,END)
    entry5.delete(0,END)


In [46]:
label1=Label(window,text="Name: ", font=("Times New Roman", 20),bd=10, justify="right", padx=20,pady=20)
label2=Label(window,text="Age: ", font=("Times New Roman", 20),bd=10, justify="right", padx=20,pady=20)
label3=Label(window,text="Contact: ", font=("Times New Roman", 20),bd=10, justify="right", padx=20,pady=20)
label4=Label(window,text="Gender: ", font=("Times New Roman", 20),bd=10, justify="right", padx=20,pady=20)
label5=Label(window,text="City: ", font=("Times New Roman", 20),bd=10, justify="right", padx=20,pady=20)
entry1=Entry(window, font=("Times New Roman", 20),bd=10, width=30, borderwidth=5)
entry2=Entry(window, font=("Times New Roman", 20),bd=10, width=30, borderwidth=5)
entry3=Entry(window, font=("Times New Roman", 20),bd=10, width=30, borderwidth=5)
entry4=Entry(window, font=("Times New Roman", 20),bd=10, width=30, borderwidth=5)
entry5=Entry(window, font=("Times New Roman", 20),bd=10, width=30, borderwidth=5)

In [47]:
add=Button(window, text="add", font=("Times New Roman", 20), bd=10, justify="right", padx=20, pady=20, command= Add)
save=Button(window, text="save", font=("Times New Roman", 20), bd=10, justify="right", padx=20, pady=20, command= Save)
clear=Button(window, text="clear", font=("Times New Roman", 20), bd=10, justify="right", padx=20, pady=20, command= Clear)
exit=Button(window, text="exit", font=("Times New Roman", 20), bd=10, justify="right", padx=20, pady=20, command= Exit)    

In [48]:
label1.grid(row=0,column=0)
label2.grid(row=1,column=0)
label3.grid(row=2,column=0)
label4.grid(row=3,column=0)
label5.grid(row=4,column=0)
entry1.grid(row=0,column=1)
entry2.grid(row=1,column=1)
entry3.grid(row=2,column=1)
entry4.grid(row=3,column=1)
entry5.grid(row=4,column=1)

In [49]:
add.grid(row=5,column=0)
save.grid(row=5,column=1)
clear.grid(row=5,column=2)
exit.grid(row=6,column=1, padx=20, pady=20)

In [50]:
window.mainloop()

# NumPy

In [51]:
import numpy as np
array1 = np.array([[1, 2, 3], [4, 5, 6]])
print("........................................................................")
print("Array:\n", array1) #array
print("........................................................................")
print("Type of the array:", type(array1)) #type of array
print("........................................................................")
print("End dimensions of the array:", array1.ndim) #no. of dimensions
print("........................................................................")
print("Size of the array:", array1.size) #total no. of elements
print("........................................................................")
print("Data type of the array elements:", array1.dtype) #data type of elements
print("........................................................................")
print("Item size in bytes:", array1.itemsize) #size of each element in bytes
print("........................................................................")
print(array1.data) #gives memory address of first element of array
print("........................................................................")
print("Total bytes consumed by the array:", array1.nbytes) #total bytes = itemsize * size
print("........................................................................")
print("Shape of the array:", array1.shape) #gives the shape of array(rows,columns)
print("........................................................................")


........................................................................
Array:
 [[1 2 3]
 [4 5 6]]
........................................................................
Type of the array: <class 'numpy.ndarray'>
........................................................................
End dimensions of the array: 2
........................................................................
Size of the array: 6
........................................................................
Data type of the array elements: int64
........................................................................
Item size in bytes: 8
........................................................................
........................................................................
Total bytes consumed by the array: 48
........................................................................
Shape of the array: (2, 3)
........................................................................


In [52]:
array1[0][0]    #[5,2,34][1,2,3]
                #    0      1

np.int64(1)

In [53]:
import numpy as np
a=np.array([[[1,2,3,4,5,6],[11,22,33,44,55,66]],[[111,222,333,444,555,666],[1111,2222,3333,4444,5555,6666]]])
print(a)
a.ndim

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]]

 [[ 111  222  333  444  555  666]
  [1111 2222 3333 4444 5555 6666]]]


3

In [54]:
a.shape   #depth=2,rows=2,column=6

(2, 2, 6)

In [55]:
a[0][1][-4]

np.int64(33)

In [56]:
a=np.array([[[1,2,3,4,5,6]]])
print(a)
a.ndim

[[[1 2 3 4 5 6]]]


3

In [57]:
a.shape   #depth=1,rows=1,column=6

(1, 1, 6)

In [58]:
a[0][0][-1] #6

np.int64(6)

In [59]:
a

array([[[1, 2, 3, 4, 5, 6]]])

### Creating Random Numbers

In [60]:
import numpy as np
print(dir(np)) 
print("......................................................................................................................................")
print(dir(np.random))

['False_', 'ScalarType', 'True_', '_CopyMode', '_NoValue', '__NUMPY_SETUP__', '__all__', '__array_api_version__', '__array_namespace_info__', '__builtins__', '__cached__', '__config__', '__dir__', '__doc__', '__expired_attributes__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__loader__', '__name__', '__numpy_submodules__', '__package__', '__path__', '__spec__', '__version__', '_array_api_info', '_core', '_distributor_init', '_expired_attrs_2_0', '_globals', '_int_extended_msg', '_mat', '_msg', '_pyinstaller_hooks_dir', '_pytesttester', '_specific_msg', '_type_info', '_typing', '_utils', 'abs', 'absolute', 'acos', 'acosh', 'add', 'all', 'allclose', 'amax', 'amin', 'angle', 'any', 'append', 'apply_along_axis', 'apply_over_axes', 'arange', 'arccos', 'arccosh', 'arcsin', 'arcsinh', 'arctan', 'arctan2', 'arctanh', 'argmax', 'argmin', 'argpartition', 'argsort', 'argwhere', 'around', 'array', 'array2string', 'array_equal', 'array_equiv', 'array_repr', 'array_split'

In [61]:
np.random.rand(50)

array([0.89165134, 0.87115901, 0.96892358, 0.90597713, 0.7171363 ,
       0.1520019 , 0.66574848, 0.45523266, 0.58467924, 0.37024887,
       0.88055476, 0.80352794, 0.77753062, 0.58852751, 0.78338321,
       0.88305309, 0.29754068, 0.38041394, 0.22222136, 0.96206966,
       0.41561286, 0.11592453, 0.70159676, 0.66072487, 0.71707838,
       0.26125027, 0.81402323, 0.79600853, 0.15803762, 0.32363034,
       0.60743828, 0.59463156, 0.62261647, 0.97145283, 0.72030238,
       0.71788587, 0.33246442, 0.42734389, 0.60601392, 0.78696417,
       0.57131503, 0.04329151, 0.33229645, 0.68045584, 0.79396349,
       0.41049572, 0.39589638, 0.96191921, 0.07894798, 0.86790344])

In [62]:
np.random.randint(1,10) #generates random integer between 1 to 10 
print(".................................................................")


.................................................................


In [63]:
a= np.random.randint(1,10,(4,3))#generates random integer between 1 to 10 
a

array([[2, 8, 9],
       [7, 2, 9],
       [1, 5, 3],
       [3, 8, 3]], dtype=int32)

In [64]:
np.zeros((9,6)) # zeros(rows,colums)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [65]:
np.zeros_like(a)  #zeros array form same as a array a 

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [66]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [67]:
np.ones_like(a)  #ones array form same as a array a 

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [68]:
np.empty([0])


array([], dtype=float64)

Arrange For Slicing

In [69]:
l=[1,2,3,4,5]
#slicing
l[2:4]

[3, 4]

In [70]:
np.arange(1,200,5) #1 to 200 with step size 5

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196])

In [71]:
np.linspace(1,100,10)  #it will create 50 numbers from 1 to 100

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [72]:
np.logspace(1,10,10)

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10])