### Numpy

- Array from numpy

### Array

- An Array is a collection of homogenous data-types. (Single data type)
- 4 byte
- Array can store data very compactly and more effcient for storing large amount of data.
- Array are great for numerical operations, list cannot directly handle math operations
- As the array size increases, numpy array get around 30 times faster than python list.
- Because the numpy array is densely packed in memory due to homogeous type, also frees the memory faster.
- you have to explicity import numpy to use array

### List

- wheras list is a collection of hetrogeneous data-types
- 14 byte
- List less effcient than array for storing large amount of data.
- its is python data type

In [ ]:
l1=[1,2,"yash"]
l2=[3,"abc","ghate"]


In [47]:
my_list=["ram",123,50.5,7+2j]
print(my_list)
type(my_list)
#whereas list is a collection of hetrogeneous data-types

['ram', 123, 50.5, (7+2j)]


list

In [1]:
import numpy as np

In [3]:
my_array1=np.array(["ram",123,50.5,7+2j])
print(my_array1)
type(my_array1)
#An array is a collection of hetrogeneous data-types

['ram' '123' '50.5' '(7+2j)']


numpy.ndarray

In [48]:
my_array=np.array([123,50.5,7+2j])
print(my_array)
type(my_array)

[123. +0.j  50.5+0.j   7. +2.j]


numpy.ndarray

In [10]:
my_array=np.array([123,50.5])  #1d array
print(my_array)
type(my_array)

[123.   50.5]


numpy.ndarray

### string>complex>float>int

#### Empty Numpy array

In [13]:
import numpy as np

In [15]:
a=np.array([])
a

array([], dtype=float64)

In [16]:
my_array=np.array([[123,50.0],[1,2]])
print(my_array)
type(my_array)

[[123.  50.]
 [  1.   2.]]


numpy.ndarray

### 1.ndim

In [17]:
# to Check dimension
my_array.ndim

2

In [4]:
my_array1.ndim

1

In [19]:
a=np.array([1,2,34])
print(a)
print("the dim is:",a.ndim)

[ 1  2 34]
the dim is: 1


In [23]:
a=np.array([[[1,2,34],[1,2,3]]])
print(a)
print("the dim is:",a.ndim)

[[[ 1  2 34]
  [ 1  2  3]]]
the dim is: 3


In [49]:
a=np.array([[[1,2,34],[1,2,3],[1,2,3]]])
print(a)
print("the dim is:",a.ndim)

[[[ 1  2 34]
  [ 1  2  3]
  [ 1  2  3]]]
the dim is: 3


### 2.dtype

In [3]:
import numpy as np

In [3]:
a=np.array([[1,2,34],[1,2,3.9]])  #dtype:
print(type(a))

print("the dim is:",a.ndim)
a.dtype

<class 'numpy.ndarray'>
the dim is: 2


dtype('float64')

In [4]:
a=np.array([[1,2,34],[1,2,3]],dtype=str)  #dtype:
print(a)
print("the dim is:",a.ndim)

[['1' '2' '34']
 ['1' '2' '3']]
the dim is: 2


In [5]:
a=np.array([[1,2,34],[1,2,3]],dtype=float)      
print(a)
print("the dim is:",a.ndim)

[[ 1.  2. 34.]
 [ 1.  2.  3.]]
the dim is: 2


In [15]:
a=np.array([['11','21','34'],['10','23','33']],dtype=float) 
print(a)

[[11. 21. 34.]
 [10. 23. 33.]]


In [29]:
a=np.array([[1,2,34],[1,2,3]],dtype=complex)     
print(a)
print("the dim is:",a.ndim)

[[ 1.+0.j  2.+0.j 34.+0.j]
 [ 1.+0.j  2.+0.j  3.+0.j]]
the dim is: 2


In [4]:
a=np.array([[1,2,34],[1,2,3.3]],dtype=str)      #dtype:
print(a)
print("the dim is:",a.ndim)

[['1' '2' '34']
 ['1' '2' '3.3']]
the dim is: 2


In [5]:
a=np.array([[5,2,34],[1,2,3]])
print(a)
print("the dim is:",a.ndim)

[[ 5  2 34]
 [ 1  2  3]]
the dim is: 2


In [6]:
a.dtype

dtype('int32')

### 3.itemsize

In [7]:
a.itemsize   #gives the size==>if int32 means 4 bytes==>gives the memory usage

4

### 4.shape

In [39]:
a.shape    #gives no. of rows and column

(2, 3)

In [9]:
b=np.array([[[1,2,34],[1,2,3],[1,2,3]]])
print(b)
b.shape   #1st gives depth,2nd gives rows and 3rd gives column

[[[ 1  2 34]
  [ 1  2  3]
  [ 1  2  3]]]


(1, 3, 3)

In [10]:
import numpy as np

# Create a 3D array with shape (2, 3, 4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print(array_3d.shape)  # Output: (2, 3, 4)

(2, 3, 4)


### 5.size

In [11]:
a.size  # provides the total number of elements in the array

6

In [10]:
b.size   #3D array dimension==>(1,3,3)==>1*3*3=9

9

### 6.data

In [41]:
a.data  #provides a buffer object that holds the raw data of the array
        #buffer object that contains the raw bytes of the array's data.

### indexing and slicing

In [44]:
a=np.array([[5,2,34],[1,2,3]])

In [46]:
a.ndim

2

In [47]:
a[0][0]    #[5,2,34][1,2,3]
           #    0      1

5

In [48]:
a[0][2]

34

In [49]:
a[1][0]

1

In [3]:
l=[2,4,5,7,8]
l[-1]

8

In [1]:
import numpy as np
a=np.array([[[1,2,3,4,5,6],[11,22,33,44,55,66]],[[111,222,333,444,555,666],[1111,2222,3333,4444,5555,6666]]])
print(a)
a.ndim

[[[   1    2    3    4    5    6]
  [  11   22   33   44   55   66]]

 [[ 111  222  333  444  555  666]
  [1111 2222 3333 4444 5555 6666]]]


3

In [7]:
a.shape   #depth=2,rows=2,column=6

(2, 2, 6)

In [7]:
a[0][0][-1]

6

In [8]:
a[1][0][-3]

444

In [52]:
a[1][1][-2]

5555

In [52]:
a[0]

array([[ 1,  2,  3,  4,  5,  6],
       [11, 22, 33, 44, 55, 66]])

In [12]:
a[2]

IndexError: index 2 is out of bounds for axis 0 with size 2

In [53]:
a[0][0]

array([1, 2, 3, 4, 5, 6])

In [54]:
a[0][1]

array([11, 22, 33, 44, 55, 66])

In [55]:
a[1][1][-1]

6666

In [53]:
a

array([[[   1,    2,    3,    4,    5,    6],
        [  11,   22,   33,   44,   55,   66]],

       [[ 111,  222,  333,  444,  555,  666],
        [1111, 2222, 3333, 4444, 5555, 6666]]])

In [1]:
import numpy as np

# Create a 3D array with shape (2, 3, 4)
array_3d = np.array([[[1, 2, 3, 4],
                      [5, 6, 7, 8],
                      [9, 10, 11, 12]],
                     
                     [[13, 14, 15, 16],
                      [17, 18, 19, 20],
                      [21, 22, 23, 24]]])

print(array_3d.shape)  # Output: (2, 3, 4)

# Accessing elements
print(array_3d[0])  # The first 2D array
print(array_3d[1, 0])  # The first row of the second 2D array
print(array_3d[1, 0, 2])  # The element in the first row, second 2D array, third column

(2, 3, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[13 14 15 16]
15


In [16]:
a

array([[[   1,    2,    3,    4,    5,    6],
        [  11,   22,   33,   44,   55,   66]],

       [[ 111,  222,  333,  444,  555,  666],
        [1111, 2222, 3333, 4444, 5555, 6666]]])

In [54]:
a[1:,1:,-2:]

array([[[5555, 6666]]])

In [3]:
a[1:,1:,-3:]

array([[[4444, 5555, 6666]]])

In [59]:
a[0:1,0:1,1:3]

array([[[2, 3]]])

In [3]:
a=np.array([[[1,2,3,4,5,6]]])
print(a)
a.ndim

[[[1 2 3 4 5 6]]]


3

In [11]:
a.shape

(1, 1, 6)

In [63]:
a[0][0][-1]

6

In [11]:
a[-1][0]

array([1, 2, 3, 4, 5, 6])

### Creating Random Numbers

In [ ]:
#random module

In [1]:
import numpy as np

In [2]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_CopyMode', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__deprecated_attrs__', '__dir__', '__doc__', '__expired_functions__', '__file__', '__former_attrs__', '__future_scalars__', '__getattr__', '__git_version__', '__loader__', '__mkl_version__', '__name__', '__package__', '__path__', '__

In [2]:
print(dir(np.random))

['BitGenerator', 'Generator', 'MT19937', 'PCG64', 'PCG64DXSM', 'Philox', 'RandomState', 'SFC64', 'SeedSequence', '__RandomState_ctor', '__all__', '__builtins__', '__cached__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '_bounded_integers', '_common', '_generator', '_mt19937', '_pcg64', '_philox', '_pickle', '_sfc64', 'beta', 'binomial', 'bit_generator', 'bytes', 'chisquare', 'choice', 'default_rng', 'dirichlet', 'exponential', 'f', 'gamma', 'geometric', 'get_bit_generator', 'get_state', 'gumbel', 'hypergeometric', 'laplace', 'logistic', 'lognormal', 'logseries', 'mtrand', 'multinomial', 'multivariate_normal', 'negative_binomial', 'noncentral_chisquare', 'noncentral_f', 'normal', 'pareto', 'permutation', 'poisson', 'power', 'rand', 'randint', 'randn', 'random', 'random_integers', 'random_sample', 'ranf', 'rayleigh', 'sample', 'seed', 'set_bit_generator', 'set_state', 'shuffle', 'standard_cauchy', 'standard_exponential', 'standard_gamma', 'sta

In [4]:
np.random.rand(50)  # generates an array of 50 random numbers drawn from a uniform distribution over the interval(0,1). 

array([0.05833566, 0.5694964 , 0.37756468, 0.12274492, 0.41930756,
       0.79717412, 0.2473099 , 0.18753515, 0.77753113, 0.11539895,
       0.28643016, 0.81043752, 0.67241825, 0.14386318, 0.62706022,
       0.77821861, 0.5520375 , 0.24242986, 0.76796902, 0.26073556,
       0.97859106, 0.12077202, 0.6345615 , 0.57519576, 0.97095151,
       0.66058432, 0.23942501, 0.82123188, 0.37491597, 0.88286061,
       0.29612028, 0.1201766 , 0.47140121, 0.68040083, 0.62668458,
       0.94950122, 0.18398453, 0.8907959 , 0.67617638, 0.12033183,
       0.42817176, 0.18567492, 0.21002614, 0.32592031, 0.78790582,
       0.22166096, 0.5863866 , 0.62427155, 0.25289356, 0.38334797])

In [6]:
np.random.rand(4,5)  #The numbers are uniformly distributed between 0 and 1.
                     #Shape: The resulting array has 4 rows and 5 columns.

array([[0.17411894, 0.10727399, 0.38149537, 0.20055032, 0.06535809],
       [0.13619199, 0.59517426, 0.95587466, 0.4715561 , 0.72763986],
       [0.42778532, 0.76118684, 0.33001271, 0.75159264, 0.49421687],
       [0.46727769, 0.54070266, 0.67738821, 0.66992227, 0.49834661]])

In [4]:
np.random.randint(1,10)  #generates random integer between 1 to 10 

8

In [5]:
np.random.randint(1,10,(4,5))  #generates random integers with 4 rows and 5 columns

array([[1, 4, 4, 3, 6],
       [8, 3, 4, 5, 6],
       [8, 9, 8, 6, 7],
       [1, 6, 5, 4, 9]])

### Numpy Functions()

### 1.array()

In [5]:
a=np.array([[5,2,34.4],[1,2,3],[1,2,3]])
a

array([[ 5. ,  2. , 34.4],
       [ 1. ,  2. ,  3. ],
       [ 1. ,  2. ,  3. ]])

### 2.zeros()

In [29]:
a=np.array([[1,2.5,3],[1,2,3],[5,6,7]])

In [30]:
a

array([[1. , 2.5, 3. ],
       [1. , 2. , 3. ],
       [5. , 6. , 7. ]])

In [31]:
a.shape

(3, 3)

In [28]:
a.ndim

2

In [10]:
np.zeros((9,6)) #zeros(rows,colums)

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [33]:
np.zeros((9))  #column 

array([0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [34]:
a

array([[1. , 2.5, 3. ],
       [1. , 2. , 3. ],
       [5. , 6. , 7. ]])

In [18]:
np.zeros_like(a)  #zeros array form same as a array a 

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### 3..ones()

In [19]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [20]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 4.empty()

In [23]:
np.empty([0])


array([], dtype=float64)

In [37]:
np.empty([5]) 

array([0.00000000e+000, 1.10485955e-311, 1.10485955e-311, 1.10485955e-311,
       3.56175136e-317])

### 5.arange()

In [ ]:
#range(start,stop,step)

In [39]:
l=[1,2,3,4,5]
#slicing
l[2:4]

[3, 4]

In [43]:
for i in range(2,8):
    print(i)


2
3
4
5
6
7


In [26]:
np.arange(1,200,5) #1 to 200 with step size 5

array([  1,   6,  11,  16,  21,  26,  31,  36,  41,  46,  51,  56,  61,
        66,  71,  76,  81,  86,  91,  96, 101, 106, 111, 116, 121, 126,
       131, 136, 141, 146, 151, 156, 161, 166, 171, 176, 181, 186, 191,
       196])

- numpy.linspace: Create an array spaced values over a specified range.
- numpy.logsapce: create an array spaced values on a logarithmic scale.

### 6.linespace()

In [19]:
np.linspace(1,100,50)  #it will create 50 numbers from 1 to 100

array([  1.        ,   3.02040816,   5.04081633,   7.06122449,
         9.08163265,  11.10204082,  13.12244898,  15.14285714,
        17.16326531,  19.18367347,  21.20408163,  23.2244898 ,
        25.24489796,  27.26530612,  29.28571429,  31.30612245,
        33.32653061,  35.34693878,  37.36734694,  39.3877551 ,
        41.40816327,  43.42857143,  45.44897959,  47.46938776,
        49.48979592,  51.51020408,  53.53061224,  55.55102041,
        57.57142857,  59.59183673,  61.6122449 ,  63.63265306,
        65.65306122,  67.67346939,  69.69387755,  71.71428571,
        73.73469388,  75.75510204,  77.7755102 ,  79.79591837,
        81.81632653,  83.83673469,  85.85714286,  87.87755102,
        89.89795918,  91.91836735,  93.93877551,  95.95918367,
        97.97959184, 100.        ])

### 7.logspace()

- Return number spaced evenly on a log scale
- LOG-Base10

In [29]:
np.logspace(1,10,30)

array([1.00000000e+01, 2.04335972e+01, 4.17531894e+01, 8.53167852e+01,
       1.74332882e+02, 3.56224789e+02, 7.27895384e+02, 1.48735211e+03,
       3.03919538e+03, 6.21016942e+03, 1.26896100e+04, 2.59294380e+04,
       5.29831691e+04, 1.08263673e+05, 2.21221629e+05, 4.52035366e+05,
       9.23670857e+05, 1.88739182e+06, 3.85662042e+06, 7.88046282e+06,
       1.61026203e+07, 3.29034456e+07, 6.72335754e+07, 1.37382380e+08,
       2.80721620e+08, 5.73615251e+08, 1.17210230e+09, 2.39502662e+09,
       4.89390092e+09, 1.00000000e+10])

### Manipulation Functions

In [3]:
import numpy as np

In [2]:
a=np.array([[5,2,34.3],[1,2,3]])
a

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

In [51]:
a.shape

(2, 3)

In [3]:
a=np.array([[[5,2,34.3],[1,2,3]]])
a

array([[[ 5. ,  2. , 34.3],
        [ 1. ,  2. ,  3. ]]])

In [4]:
a.shape

(1, 2, 3)

In [7]:
a=np.array([[[5,2,34.3]],[[1,2,3]]])
a

array([[[ 5. ,  2. , 34.3]],

       [[ 1. ,  2. ,  3. ]]])

In [8]:
a.shape

(2, 1, 3)

In [11]:
a=np.array([[[[5,2,34.3]],[[1,2,3]]]])
a

array([[[[ 5. ,  2. , 34.3]],

        [[ 1. ,  2. ,  3. ]]]])

In [13]:
a.shape

(1, 2, 1, 3)

In [5]:
b=np.array([[[[1,2,3,4],[2,3,4,5]],[[5,6,7,8],[7,5,8,9]]]])

In [7]:
b

array([[[[1, 2, 3, 4],
         [2, 3, 4, 5]],

        [[5, 6, 7, 8],
         [7, 5, 8, 9]]]])

In [9]:
b.shape

(1, 2, 2, 4)

### 1. reshape()

#reshape uses multiples of no.of elements

In [11]:
#6: (6,1),(2,3),(3,2),(1,6)

In [40]:
a=np.array([[5,2,34.3],[1,2,3]])
a

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

In [41]:
a.shape

(2, 3)

In [43]:
a.reshape(1,6)

array([[ 5. ,  2. , 34.3,  1. ,  2. ,  3. ]])

In [42]:
a.reshape(3,8)   #convert size 6 to (3,8)

ValueError: cannot reshape array of size 6 into shape (3,8)

In [44]:
a=np.array([[[[5,2,34.3]],[[1,2,3]],[[2,3,4]]]]) #(1,3,1,3)==>(1,9),(3,3),(9,1)
a

array([[[[ 5. ,  2. , 34.3]],

        [[ 1. ,  2. ,  3. ]],

        [[ 2. ,  3. ,  4. ]]]])

In [45]:
a.reshape(1,9)

array([[ 5. ,  2. , 34.3,  1. ,  2. ,  3. ,  2. ,  3. ,  4. ]])

In [16]:
a.reshape(9,1)

array([[ 5. ],
       [ 2. ],
       [34.3],
       [ 1. ],
       [ 2. ],
       [ 3. ],
       [ 2. ],
       [ 3. ],
       [ 4. ]])

In [47]:
a=np.random.randint(1,10,(5,10))
a

array([[8, 1, 9, 2, 1, 7, 6, 8, 2, 9],
       [2, 4, 5, 3, 1, 1, 6, 7, 1, 8],
       [9, 5, 9, 4, 3, 3, 6, 6, 4, 8],
       [7, 5, 8, 9, 9, 4, 7, 9, 3, 9],
       [3, 5, 7, 4, 7, 2, 8, 8, 4, 1]])

In [48]:
#50=(5,10),(50,1),(2,25),(25,2),(1,50)

In [49]:
b=a.reshape(25,2)
b

array([[8, 1],
       [9, 2],
       [1, 7],
       [6, 8],
       [2, 9],
       [2, 4],
       [5, 3],
       [1, 1],
       [6, 7],
       [1, 8],
       [9, 5],
       [9, 4],
       [3, 3],
       [6, 6],
       [4, 8],
       [7, 5],
       [8, 9],
       [9, 4],
       [7, 9],
       [3, 9],
       [3, 5],
       [7, 4],
       [7, 2],
       [8, 8],
       [4, 1]])

In [50]:
b=a.reshape(2,25)
b

array([[8, 1, 9, 2, 1, 7, 6, 8, 2, 9, 2, 4, 5, 3, 1, 1, 6, 7, 1, 8, 9, 5,
        9, 4, 3],
       [3, 6, 6, 4, 8, 7, 5, 8, 9, 9, 4, 7, 9, 3, 9, 3, 5, 7, 4, 7, 2, 8,
        8, 4, 1]])

In [60]:
v=np.array([1,2,3,5],ndmin=5)

In [98]:
print(v)
v.shape

[[[[[1 2 3 5]]]]]


(1, 1, 1, 1, 4)

In [78]:
#no.of rows=1

In [82]:
v1=np.array([[1,2,3,5],[7,8,9,7]],ndmin=3)

In [83]:
v1

array([[[1, 2, 3, 5],
        [7, 8, 9, 7]]])

In [84]:
v1.shape #(1,2,4)

(1, 2, 4)

In [85]:
v2=np.array([[1,2,3,5],[7,8,9,7]],ndmin=2)

In [86]:
v2

array([[1, 2, 3, 5],
       [7, 8, 9, 7]])

In [87]:
v2.shape

(2, 4)

In [21]:
v3=np.array([[1,2,3,5],[7,8,9,7]],ndmin=4)

In [22]:
v3

array([[[[1, 2, 3, 5],
         [7, 8, 9, 7]]]])

In [23]:
v3.shape  #(1,1,2,4)

(1, 1, 2, 4)

In [24]:
v4=v3.reshape(4,2)  #rows=4,columns=2

In [25]:
v4

array([[1, 2],
       [3, 5],
       [7, 8],
       [9, 7]])

In [58]:
v4.shape

(4, 2)

In [61]:
v

array([[[[[1, 2, 3, 5]]]]])

In [62]:
v.shape

(1, 1, 1, 1, 4)

In [105]:
v4=v.reshape(2,2,1) #matrix or depth=2, rows=2,col=1
print(v4)
v4.ndim

[[[1]
  [2]]

 [[3]
  [5]]]


3

In [106]:
v4=v.reshape(2,2,-1) #matrix or depth=2, rows=2,col=1
print(v4)
v4.ndim

[[[1]
  [2]]

 [[3]
  [5]]]


3

In [112]:
c=np.array([1,2,3,5,7,8],ndmin=5)
c

array([[[[[1, 2, 3, 5, 7, 8]]]]])

In [120]:
c1=c.reshape(3,2,-1)  # -1==>Automatically calculates the number of columns
print(c1)
c1.ndim

[[[1]
  [2]]

 [[3]
  [5]]

 [[7]
  [8]]]


3

In [74]:
v

array([[[1],
        [2]],

       [[3],
        [5]],

       [[7],
        [8]],

       [[9],
        [7]]])

In [73]:
v=v.reshape(4,2,2) 
v.ndim

ValueError: cannot reshape array of size 8 into shape (4,2,2)

### 2.Transpose()

In [9]:
import numpy as np
y=np.array([[1,2,3,4],[5,6,7,8]])
y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [11]:
y.transpose()

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [1]:
import numpy as np
y=np.array([[[1,2,3,4],[5,6,7,8],[3,7,6,5]]])
y

y.transpose()  #(1,3,4)==>(4,3,1)==>(0,1,2)

array([[[1],
        [5],
        [3]],

       [[2],
        [6],
        [7]],

       [[3],
        [7],
        [6]],

       [[4],
        [8],
        [5]]])

In [67]:
y = np.array([[[1, 2, 3, 4],
               [5, 6, 7, 8],
               [3, 7, 6, 5]]])


In [71]:
np.transpose(y)  #original shape(1,3,4)==>(0,1,2)==>(depth,rows,columns)

array([[[1],
        [5],
        [3]],

       [[2],
        [6],
        [7]],

       [[3],
        [7],
        [6]],

       [[4],
        [8],
        [5]]])

In [75]:
y_trans = np.transpose(y, (0, 2, 1))  #original shape(1,3,4)==>transpose shape(0,2,1)==>axis0=depth,axis2=4 rows,axis1=3 columns
y_trans

array([[[1, 5, 3],
        [2, 6, 7],
        [3, 7, 6],
        [4, 8, 5]]])

In [77]:
y_trans = np.transpose(y, (1, 0, 2))  #original shape(1,3,4)==>(1,0,2)==>axis1=3-depth,axis0=1-rows,axis2=4-columns==># Shape: (3, 1, 4)
y_trans

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]],

       [[3, 7, 6, 5]]])

### 3.flatten

In [1]:
import numpy as np

# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Flatten the array
flattened_array = array_2d.flatten()

print("Original array:")
print(array_2d)

print("Flattened array:")
print(flattened_array)

Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened array:
[1 2 3 4 5 6 7 8 9]


### 4.concatenate()

In [148]:
a

array([[1, 2, 3],
       [2, 3, 4]])

In [149]:
np.concatenate(a)

array([1, 2, 3, 2, 3, 4])

In [51]:
y=np.array([[[1,2,3,4]],[[5,6,7,8]]])
y

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [64]:
y.ndim

3

In [35]:
np.concatenate(y)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [26]:
import numpy as np

# Create two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenate along the default axis (0)
result = np.concatenate((array1, array2))

print("Concatenated array:")
print(result)

Concatenated array:
[1 2 3 4 5 6]


### 4. vstack()

In [52]:
y

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [38]:
np.vstack(y)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
array1 = np.array([[1, 2, 3]])
array2 = np.array([[4, 5, 6]])
array3 = np.array([[4, 5, 7]])
result = np.vstack((array1, array2,array3))
result

array([[1, 2, 3],
       [4, 5, 6],
       [4, 5, 7]])

In [5]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])

result = np.vstack((a, b))
print(result)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### 5. hstack()

In [53]:
y

array([[[1, 2, 3, 4]],

       [[5, 6, 7, 8]]])

In [39]:
np.hstack(y)

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [65]:
a

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

In [66]:
np.vstack(a)

array([[ 5. ,  2. , 34.3],
       [ 1. ,  2. ,  3. ]])

In [67]:
np.hstack(a)

array([ 5. ,  2. , 34.3,  1. ,  2. ,  3. ])

In [3]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])
result = np.hstack((array1, array2))
result

array([1, 2, 3, 4, 5, 6])

In [2]:
import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10]])

result = np.hstack((a, b))
print(result)

[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]


In [2]:
import numpy as np
a=np.random.rand(4,2) #rand:floating number
print(a)
a.ndim

[[0.79149316 0.08435708]
 [0.50636454 0.90290656]
 [0.37916432 0.88578464]
 [0.89749519 0.99689877]]


2

In [3]:
a=np.random.rand(1,4,2) #(matrix,rows,columns) #rand:floating number
print(a)
a.ndim

[[[0.19176093 0.1231189 ]
  [0.8899266  0.94707898]
  [0.56342916 0.59365934]
  [0.11557726 0.31972172]]]


3

In [40]:
a=np.random.rand(3,4,2) #(matrix,rows,columns) #rand:floating number
print(a)
a.ndim

[[[0.66732537 0.33632618]
  [0.64332295 0.21359499]
  [0.51783702 0.07178972]
  [0.0761507  0.12543084]]

 [[0.36174516 0.23644534]
  [0.99414511 0.80439545]
  [0.12764111 0.81437298]
  [0.05242821 0.21359475]]

 [[0.49189495 0.40376505]
  [0.36346114 0.04853368]
  [0.76990023 0.15617501]
  [0.33645092 0.8479903 ]]]


3

In [91]:
np.random.randint(1,10,(2,3))  #randint(range,(rows,col))

array([[7, 4, 9],
       [9, 2, 7]])

In [93]:
x=np.random.randint(1,10,(6,6))  #36=(2,18),(3,12),(12,3)
x

array([[6, 3, 1, 1, 1, 7],
       [3, 7, 5, 3, 7, 5],
       [9, 5, 4, 2, 3, 8],
       [5, 7, 5, 1, 6, 5],
       [8, 8, 4, 8, 6, 8],
       [9, 5, 4, 8, 5, 1]])

In [94]:
x.reshape(12,3)

array([[6, 3, 1],
       [1, 1, 7],
       [3, 7, 5],
       [3, 7, 5],
       [9, 5, 4],
       [2, 3, 8],
       [5, 7, 5],
       [1, 6, 5],
       [8, 8, 4],
       [8, 6, 8],
       [9, 5, 4],
       [8, 5, 1]])

In [95]:
x.reshape(2,18)

array([[6, 3, 1, 1, 1, 7, 3, 7, 5, 3, 7, 5, 9, 5, 4, 2, 3, 8],
       [5, 7, 5, 1, 6, 5, 8, 8, 4, 8, 6, 8, 9, 5, 4, 8, 5, 1]])

In [96]:
np.random.randint(1,100,(5,2))

array([[50, 17],
       [95, 50],
       [61, 64],
       [ 3, 29],
       [ 4, 55]])

In [2]:
import numpy as np

In [13]:
a=np.random.randint(1,100,(1,100))
a

array([[91, 28,  7, 38, 78, 66, 65, 81, 43, 86, 47,  8, 10, 59, 76, 86,
        55, 80, 11, 84, 24, 88,  8, 47, 55, 82, 32,  7, 61, 76, 31, 46,
        47, 79, 11, 64, 40, 83, 96, 84, 95, 35, 41,  7, 24, 19, 76,  8,
        38, 23, 96, 94,  5, 61, 46, 73, 39,  8, 95, 97,  7, 80, 71, 47,
         2, 78, 88, 38, 88, 54,  7, 19, 96,  3, 87, 21, 45, 73, 25, 35,
        35, 82, 21, 82,  4, 35, 68, 37, 19, 73, 29,  9, 24, 55, 18, 29,
        66, 66, 72, 86]])

### 6. split
- Splits an array into multiple sub-array

In [2]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Split into 3 equal parts
split_array = np.split(array_1d, 3)

print("Split array:")
print(split_array)

Split array:
[array([1, 2]), array([3, 4]), array([5, 6])]


In [3]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Split along the first axis (rows)
split_array_2d = np.split(array_2d, 3, axis=0)

print("Split 2D array:")
print(split_array_2d)

Split 2D array:
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
#If the array cannot be split evenly, np.split() will raise a ValueError

In [16]:
e=np.arange(0,10)
e

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.split(e,5)

[array([0, 1]), array([2, 3]), array([4, 5]), array([6, 7]), array([8, 9])]

In [20]:
np.split(e,2)

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9])]

In [22]:
np.split(e,3)

ValueError: array split does not result in an equal division

In [25]:
np.split(e,15)

ValueError: array split does not result in an equal division

In [29]:
a,b=np.split(e,2)

In [31]:
a

array([0, 1, 2, 3, 4])

In [33]:
b

array([5, 6, 7, 8, 9])

In [35]:
a,b,c,d,q=np.split(e,5)

In [37]:
a

array([0, 1])

In [39]:
b

array([2, 3])

In [41]:
c

array([4, 5])

In [43]:
d

array([6, 7])

In [45]:
q

array([8, 9])

### 7.delete

In [47]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])
arr = np.delete(arr, 2)  # Removes the element at index 2
print(arr)  # Output: [10 20 40 50]


[10 20 40 50]


In [5]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

# Delete the second row (index 1)
modified_array_2d_row = np.delete(array_2d, 1, axis=0)

print("Modified 2D array after deleting row at index 1:")
print(modified_array_2d_row)

Modified 2D array after deleting row at index 1:
[[1 2 3]
 [7 8 9]]


In [6]:
# Delete the first column (index 0)
modified_array_2d_col = np.delete(array_2d, 0, axis=1)

print("Modified 2D array after deleting column at index 0:")
print(modified_array_2d_col)

Modified 2D array after deleting column at index 0:
[[2 3]
 [5 6]
 [8 9]]


In [49]:
import numpy as np

arr = np.array([
    [[ 1,  2,  3,  4],
     [ 5,  6,  7,  8],   # First depth slice (index 0)
     [ 9, 10, 11, 12]],
    
    [[13, 14, 15, 16],
     [17, 18, 19, 20],   # Second depth slice (index 1)
     [21, 22, 23, 24]]])

print("Shape:", arr.shape)
print("3D Array:\n", arr)


Shape: (2, 3, 4)
3D Array:
 [[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [53]:
new_arr = np.delete(arr, 1, axis=1)  #deletes a row
print(new_arr)
print(new_arr.shape)  # (2, 2, 4)  #(0,1,2)


[[[ 1  2  3  4]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [21 22 23 24]]]
(2, 2, 4)


In [55]:
new_arr = np.delete(arr, 2, axis=2)  #deletes a column
print(new_arr)
print(new_arr.shape)  # (2, 3, 3)


[[[ 1  2  4]
  [ 5  6  8]
  [ 9 10 12]]

 [[13 14 16]
  [17 18 20]
  [21 22 24]]]
(2, 3, 3)


In [57]:
new_arr = np.delete(arr, 0, axis=0)  #deletes a depth
print(new_arr)
print(new_arr.shape)  # (1, 3, 4)


[[[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
(1, 3, 4)


### 8.insert

In [7]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3, 4])

# Insert a value (99) at index 2
modified_array = np.insert(array_1d, 2, 99)

print("Original array:")
print(array_1d)
print("Modified array after inserting 99 at index 2:")
print(modified_array)

Original array:
[1 2 3 4]
Modified array after inserting 99 at index 2:
[ 1  2 99  3  4]


In [8]:
# Insert multiple values (10 and 20) at index 1
modified_array_multiple = np.insert(array_1d, 1, [10, 20])

print("Modified array after inserting 10 and 20 at index 1:")
print(modified_array_multiple)

Modified array after inserting 10 and 20 at index 1:
[ 1 10 20  2  3  4]


In [9]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Insert a new row at index 1
modified_array_2d_row = np.insert(array_2d, 1, [7, 8, 9], axis=0)

print("Modified 2D array after inserting a new row at index 1:")
print(modified_array_2d_row)

Modified 2D array after inserting a new row at index 1:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [10]:
# Insert a new column at index 0
modified_array_2d_col = np.insert(array_2d, 0, [10, 11], axis=1)

print("Modified 2D array after inserting a new column at index 0:")
print(modified_array_2d_col)

Modified 2D array after inserting a new column at index 0:
[[10  1  2  3]
 [11  4  5  6]]


### 9.append

In [12]:
import numpy as np

# Create a 1D array
array_1d = np.array([1, 2, 3])

# Append a single value (4)
modified_array = np.append(array_1d, 4)

print("Original array:")
print(array_1d)
print("Modified array after appending 4:")
print(modified_array)


Original array:
[1 2 3]
Modified array after appending 4:
[1 2 3 4]


In [13]:
# Append multiple values (5 and 6)
modified_array_multiple = np.append(array_1d, [5, 6])

print("Modified array after appending 5 and 6:")
print(modified_array_multiple)

Modified array after appending 5 and 6:
[1 2 3 5 6]


In [14]:
# Create a 2D array
array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])

# Append a new row
modified_array_2d_row = np.append(array_2d, [[7, 8, 9]], axis=0)

print("Modified 2D array after appending a new row:")
print(modified_array_2d_row)

Modified 2D array after appending a new row:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
# Append a new column
modified_array_2d_col = np.append(array_2d, [[7], [8]], axis=1)

print("Modified 2D array after appending a new column:")
print(modified_array_2d_col)

Modified 2D array after appending a new column:
[[1 2 3 7]
 [4 5 6 8]]


## Full

- Return a new array of given shape and types,filled with fill_value.

In [46]:
np.full((5,5),100)  #gives an array of 5 rows and 5 columns filled with value 100

array([[100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100],
       [100, 100, 100, 100, 100]])

In [49]:
a=np.full((4,8),"ms")
a

array([['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms'],
       ['ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms', 'ms']], dtype='<U2')

In [51]:
np.full_like(a,45)  #gives same dimension array as array have filled with value 45

array([['45', '45', '45', '45', '45', '45', '45', '45'],
       ['45', '45', '45', '45', '45', '45', '45', '45'],
       ['45', '45', '45', '45', '45', '45', '45', '45'],
       ['45', '45', '45', '45', '45', '45', '45', '45']], dtype='<U2')

## eye

- Return a 2-D array with ones on the diagonal and zero elsewhere.

In [14]:
np.eye(6,6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [103]:
np.eye(5,7)

array([[1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0.]])

In [2]:
import numpy as np
np.eye(10,10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [5]:
np.eye(5,k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [10]:
np.eye(10,k=-1)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]])

## Numpy Searching Array using where

In [8]:
z=np.arange(3,51)
z

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [9]:
np.where(z<30)

#it gives position/index of that element which satisfy the condition

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26], dtype=int64),)

In [110]:
np.where(z%2==0)   #returns the index value==>z=4==>returns 1 for z=4

(array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
        35, 37, 39, 41, 43, 45], dtype=int64),)

In [111]:
np.where(z==6)  #returns the index value where z==6

(array([3], dtype=int64),)

### Arithematic Operations in numpy

In [35]:
import pandas as pd

C:\Users\admin\anaconda3\Lib\site-packages\pandas\core\arrays\masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (


In [43]:
a1=pd.Series([1,2,3,4,5,6])

In [38]:
a1

0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64

In [44]:
a2=pd.Series([10,20,30,40,50,60])

In [45]:
a2

0    10
1    20
2    30
3    40
4    50
5    60
dtype: int64

In [46]:
a1+a2

0    11
1    22
2    33
3    44
4    55
5    66
dtype: int64

In [1]:
import numpy as np

In [2]:
a=np.array([[1,2,10],[5,7,8]])
b=np.array([[10,20,7],[50,70,7]])

In [3]:
a

array([[ 1,  2, 10],
       [ 5,  7,  8]])

In [4]:
b

array([[10, 20,  7],
       [50, 70,  7]])

### add()

In [5]:
a+b   #using operators(+)

array([[11, 22, 17],
       [55, 77, 15]])

In [6]:
np.add(a,b)

array([[11, 22, 17],
       [55, 77, 15]])

In [61]:
np.nan

nan

In [12]:
a=np.array([[1,2,10],[5,7,np.nan]])
b=np.array([[10,20,7],[50,70,7]])

In [13]:
a+b

array([[11., 22., 17.],
       [55., 77., nan]])

In [5]:
a=np.array([[1,2,10],[5,7,np.nan],[1,2,3]])
b=np.array([[10,20,7],[50,70,7]])

In [7]:
a+b

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

In [12]:
arr1=np.array([[1,2,3],[2,3,4]])
arr2=np.array([[1,2],[1,2]])
arr=arr1+arr2
arr

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

In [9]:
a=np.array([[[1,2,10],[5,7,np.nan]]])
b=np.array([[[10,20,7],[50,70,7]]])

In [11]:
a+b

array([[[11., 22., 17.],
        [55., 77., nan]]])

### sub()

In [15]:
a=np.array([[1,2,10],[5,7,8]])
b=np.array([[10,20,7],[50,70,7]])

In [16]:
np.subtract(a,b)

array([[ -9, -18,   3],
       [-45, -63,   1]])

### mult()

In [124]:
np.multiply(a,b)

array([[ 10,  40,  70],
       [250, 490,  56]])

In [10]:
a=np.array([[1,2,3],[2,3,np.nan]])
b=np.array([[1,2,3],[2,3,4]])


In [12]:
a*b

array([[ 1.,  4.,  9.],
       [ 4.,  9., nan]])

In [14]:
np.divide(a,b)

array([[ 1.,  1.,  1.],
       [ 1.,  1., nan]])

In [16]:
a

array([[ 1.,  2.,  3.],
       [ 2.,  3., nan]])

In [18]:
b

array([[1, 2, 3],
       [2, 3, 4]])

In [20]:
np.mod(a,b)   #modulus operation==>gives remainder

array([[ 0.,  0.,  0.],
       [ 0.,  0., nan]])

In [7]:
a=np.array([[10,20,30],[20,30,40]])
b=np.array([[1,2,4],[2,3,4]])


In [65]:
np.mod(a,b)

array([[0, 0, 2],
       [0, 0, 0]])

In [8]:
a**b

array([[     10,     400,  810000],
       [    400,   27000, 2560000]])

In [67]:
np.power(a,b)

array([[     10,     400,  810000],
       [    400,   27000, 2560000]])

### Statistics

In [131]:
import numpy as np

In [9]:
s=np.array([[50,10,30,],[500,100,300,],[5,1,3]])
s.ndim

2

In [69]:
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [78]:
l=[1,2,8,9]
max(l)

9

In [22]:
b=np.array([[52,17,2],[50,140,150],[15,1,3]])
b

array([[ 52,  17,   2],
       [ 50, 140, 150],
       [ 15,   1,   3]])

In [24]:
np.amax(b)

150

In [26]:
np.amin(b)

1

In [28]:
b

array([[ 52,  17,   2],
       [ 50, 140, 150],
       [ 15,   1,   3]])

In [30]:
np.amin(b,axis=0)  #axis=0 finds min value for each column

array([15,  1,  2])

In [32]:
np.amin(b,axis=1)  #axis=1 finds min value for each row

array([ 2, 50,  1])

In [34]:
b

array([[ 52,  17,   2],
       [ 50, 140, 150],
       [ 15,   1,   3]])

In [85]:
np.amax(b,axis=0)  

array([ 52, 140, 150])

In [86]:
np.amax(b,axis=1)       

array([ 52, 150,  15])

In [88]:
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [89]:
np.amin(s,axis=0)

array([5, 1, 3])

In [90]:
np.amin(s,axis=1)

array([ 10, 100,   1])

In [91]:
np.amax(s)

500

In [92]:
np.amin(s)

1

In [10]:
s

array([[ 50,  10,  30],
       [500, 100, 300],
       [  5,   1,   3]])

In [93]:
np.amax(s,axis=0)

array([500, 100, 300])

In [94]:
np.amax(s,axis=1)

array([ 50, 500,   5])

In [75]:
b

array([[ 52,  17,   4],
       [ 50, 140, 150],
       [ 15,   1,   3]])

In [96]:
np.mean(b)

48.0

In [27]:
(52+50+15+17+140+1+150+4+3)/9

48.0

In [106]:
a=np.var(b) #variance
a

3012.0

In [29]:
(52-48)**2

16

In [30]:
(50-48)**2

4

In [39]:
(16+4+1089+961+8464+2209+10404+1936+2025)/9

3012.0

In [107]:
import math
math.sqrt(a)

54.881690936048976

In [109]:
np.std(b)  #std=standard deviation==>square root of variance

54.881690936048976

### Datatype

- The main several data types supported by NumPy Python are
- np.bool_: This type is used to return boolean values like (True or False).
- np.int: It is the default type of integer and C-type long.
- intc: It is similar to C integer and it indicates 32 or 64 bit integer.
- intp: This type indicates for indexing.
- int8: By default its range value is -128 to 127.
- int16: It is a 16 bit integer and by default its range value is (-32768 to 32767).
- int32: it is for set 32-bit integer and the range value is (-2147483648 to 2147483647).
- int64: By default its value is set at (-9223372036854775808 to 9223372036854775807).
- uint8: It is a 8 bit integer and range value is (0 to 255).
- uint16: It is a 16 bit unsigned integer and range value is (0 to 65535).
- uint32: This is a unsigned integer with 32 bit and its value is (0 to 4294967295).
- uint64: It is a 8 byte unsigned integer and range value is (0 to 18446744073709551615).

In [77]:
a=np.array([2555])
a.dtype


dtype('int32')

In [78]:
a=np.array([2])
a.dtype

dtype('int32')

In [53]:
a=np.array([789])
a.dtype


dtype('int32')

In [114]:
a=np.array([12,2,3,6],dtype=np.float16)
print(a.dtype)
a

float16


array([12.,  2.,  3.,  6.], dtype=float16)

In [59]:
s=np.array([4,5,6,78.0,"sadbgv"])
print(s)

print(s.dtype)   #U32==>32-bit unsigned integer

['4' '5' '6' '78.0' 'sadbgv']
<U32


In [164]:
a

array([12.,  2.,  3.,  6.], dtype=float16)

In [115]:
np.array('1999-06-14')

array('1999-06-14', dtype='<U10')

In [60]:
np.array(np.datetime64('1999-06-14'))

array('1999-06-14', dtype='datetime64[D]')

In [117]:
b=np.array([1,2,3])

In [118]:
b.astype("str")

array(['1', '2', '3'], dtype='<U11')

In [170]:
b.astype("f")

array([1., 2., 3.], dtype=float32)

In [11]:
np.iinfo(np.int8)

iinfo(min=-128, max=127, dtype=int8)

In [172]:
np.iinfo(np.int8).min

-128

### Copy and View in Numpy

### Copy
Copying: Using np.copy() creates a new array. Changes to the copied array will not affect the original.


In [2]:
import numpy as np

# Create an original array
original_array = np.array([1, 2, 3, 4])

# Create a copy of the original array
copied_array = np.copy(original_array)

# Modify the copied array
copied_array[0] = 10

print("Original Array:", original_array)  
print("Copied Array:", copied_array)      

Original Array: [1 2 3 4]
Copied Array: [10  2  3  4]


### View
Viewing: Simply assigning an array to another variable does not create a new array. Both variables will refer to the same data, and changes to one will affect the other.

In [4]:
# Reference the original array
viewed_array = original_array

# Modify the viewed array
viewed_array[0] = 99

print("Original Array after modification:", original_array)  
print("Viewed Array:", viewed_array)                         

Original Array after modification: [99  2  3  4]
Viewed Array: [99  2  3  4]


### Sort in Numpy

In [42]:
import numpy as np

# Create an array
array = np.array([3, 1, 4, 1, 5, 9, 2])

# Sort the array
sorted_array = np.sort(array) #function returns a sorted copy of the array.

print("Original Array:", array)   
print("Sorted Array:", sorted_array)  

Original Array: [3 1 4 1 5 9 2]
Sorted Array: [1 1 2 3 4 5 9]


In [48]:
import numpy as np

# Create an array
array = np.array([10, 3, 5, 1, 9])

# Sort the array in descending order
sorted_array = np.sort(array)[::-1]

print(sorted_array)


[10  9  5  3  1]


In [46]:
import numpy as np

# Create an array
array = np.array([3, 1, 4, 1, 5, 9, 2])

# Sort the array
sorted_array = sorted(array,reverse=True) #function returns a sorted copy of the array.

print("Original Array:", array)   
print("Sorted Array:", sorted_array) 

Original Array: [3 1 4 1 5 9 2]
Sorted Array: [9, 5, 4, 3, 2, 1, 1]
